# Generated by Django 5.2.5 on 2025-08-30 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boosttype',
            options={'ordering': ['boost_type', 'consecutive_days_required'], 'verbose_name': 'Тип бонуса', 'verbose_name_plural': 'Типы бонусов'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-created_at'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='playerquest',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Выполнение задания игроком', 'verbose_name_plural': 'Выполнения заданий игроками'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['difficulty', 'created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='boosttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего очков'),
        ),
        migrations.AddField(
            model_name='playerquest',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс (%)'),
        ),
        migrations.AddField(
            model_name='quest',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Легкое'), (2, 'Среднее'), (3, 'Сложное')], default=1, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='quest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_boosts', to='bonuses.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='player',
            name='consecutive_login_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Дней подряд'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_login_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего входа'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_login_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего входов'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='playerquest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='playerquest',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='playerquest',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to='bonuses.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='playerquest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuses.quest', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['player', 'awarded_at'], name='bonuses_boo_player__a838c8_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['awarded_at'], name='bonuses_boo_awarded_9afcbb_idx'),
        ),
    ]
