# Generated by Django 5.2.5 on 2025-08-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_alter_boosttype_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок уровня')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название приза')),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
            },
        ),
        migrations.RemoveField(
            model_name='quest',
            name='boost_type',
        ),
        migrations.AlterUniqueTogether(
            name='playerquest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playerquest',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerquest',
            name='quest',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='consecutive_login_days',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_login_days',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='ID игрока'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Счет')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuses.level', verbose_name='Уровень')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuses.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Прохождение уровня',
                'verbose_name_plural': 'Прохождения уровней',
                'unique_together': {('player', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LevelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuses.level', verbose_name='Уровень')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuses.prize', verbose_name='Приз')),
            ],
            options={
                'verbose_name': 'Приз за уровень',
                'verbose_name_plural': 'Призы за уровни',
                'unique_together': {('level', 'prize')},
            },
        ),
        migrations.DeleteModel(
            name='Boost',
        ),
        migrations.DeleteModel(
            name='BoostType',
        ),
        migrations.DeleteModel(
            name='PlayerQuest',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
